<div class="footer-showroom-container">
	<div class="footer-showroom-content">
		<div class="showroom footer-showroom-left-img">
			<?= $block->getLayout()
			->createBlock('Magento\Cms\Block\Block')
			->setBlockId('burning-footer-showroom-left-img')
			->toHtml() ?>
		</div>
		<div class="showroom footer-showroom-center">
			<?= $block->getLayout()
			->createBlock('Magento\Cms\Block\Block')
			->setBlockId('burning-footer-showroom-center')
			->toHtml() ?>
		</div>
		<div class="showroom footer-showroom-right-img">
			<?= $block->getLayout()
			->createBlock('Magento\Cms\Block\Block')
			->setBlockId('burning-footer-showroom-right-img')
			->toHtml() ?>
		</div>
	</div>
</div>
