<div class="banner__end_mobile">
    <div class="banner_04">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_banner_image_mobile_04')->toHtml(); ?>
        <div class="banner_04_content">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_banner_content_mobile_04')->toHtml(); ?>
        </div>
    </div>
    <div class="banner_05">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_banner_image_mobile_05')->toHtml(); ?>
        <div class="banner_05_content">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_banner_content_mobile_05')->toHtml(); ?>
        </div>
    </div>
    <div class="banner_06">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_banner_image_mobile_06')->toHtml(); ?>
        <div class="banner_06_content">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_banner_content_mobile_06')->toHtml(); ?>
        </div>
    </div>
</div>
<div class="banner__end_desktop">
    <div class="banner_04">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_banner_image_desktop_04')->toHtml(); ?>
        <div class="banner_04_content">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_banner_content_mobile_04')->toHtml(); ?>
        </div>
    </div>
    <div class="banner_05">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_banner_image_desktop_05')->toHtml(); ?>
        <div class="banner_05_content">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_banner_content_mobile_05')->toHtml(); ?>
        </div>
    </div>
    <div class="banner_06">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_banner_image_desktop_06')->toHtml(); ?>
        <div class="banner_06_content">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_banner_content_mobile_06')->toHtml(); ?>
        </div>
    </div>
</div>

