<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
?>

<?php if ($block->canShowBlock()) : ?>
    <div class="block filter" id="layered-filter-block">

        <a class="refine_by" href="javascript:void(0)">Filter by</a>
        <!--  Can hang ngang -->
        <div class="block-content filter-content">

        <?php endif; ?>
        <?php $wrapOptions = false; ?>
        <?php foreach ($block->getFilters() as $filter) : ?>
            <?php if ($filter->getItemsCount()) : ?>
                <?php if (!$wrapOptions) : ?>

                    <!-- Add refine -->
                    <div class="filter-options filter-options-refine">
                        <div class="filter-options-item active filter-options-item-refine">
                            <div class="filter-options-title filter-options-title-refine"> Shoppping Options </div>
                            <div><span class="close"></span></div>
                        </div>
                    </div>
                    <!-- end add refine -->


                    <!-- Accordion -->
                    <div class="filter-options" id="narrow-by-list" data-role="content" data-mage-init='
                    {
                        "accordion":
                        {
                            "active": false,
                            "openedState": "active",
                            "collapsible": true,
                            "multipleCollapsible": false
                        }
                    }'>
                    <?php $wrapOptions = true;
                endif; ?>
                    <?php if ($filter->getItemsCount()) : ?>
                        <div data-role="collapsible" class="filter-options-item">
                            <div data-role="title" class="filter-options-title">
                                <?= 'filter' ?>
                                <?= $block->escapeHtml(__($filter->getName())) ?></div>
                            <div data-role="content" class="filter-options-content"><?= /* @noEscape */ $block->getChildBlock('renderer')->render($filter) ?></div>
                        </div>
                    <?php endif ?>
                <?php endif; ?>
            <?php endforeach; ?>
            <?php if ($wrapOptions) : ?>
                    </div>


                    <!-- Di chuyen khoi state xuong duoi options -->
                    <?= $block->getChildHtml('state') ?>
                    <?php if ($block->getLayer()->getState()->getFilters()) : ?>
                        <!--  -->

                    <?php else : ?>
                        <script>
                            require([
                                'jquery'
                            ], function($) {
                                $('#layered-filter-block').addClass('filter-no-options');
                            });
                        </script>
                    <?php endif; ?>
        </div>
    </div>
<?php endif; ?>

<script>
    require([
        'jquery'
    ], function($) {
        $(function() {
            $('.refine_by').click(function() {
                $('.filter-content').toggleClass('active');
                $('.header').hide();
                $('.nav-sections').hide();
            });
            $('.close').click(function() {
                $('.filter-content').toggleClass('active');
                $('.header').show();
                $('.nav-sections').show();
            });
        })
    });
</script>