<div class="banner__between_mobile">
    <div class="banner_02">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_banner_image_mobile_02')->toHtml(); ?>
        <div class="banner_02_content">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_banner_content_mobile_02')->toHtml(); ?>
        </div>
    </div>
    <div class="banner_03">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_banner_image_mobile_03')->toHtml(); ?>
        <div class="banner_03_content">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_banner_content_mobile_03')->toHtml(); ?>
        </div>
    </div>
</div>
<div class="banner__between_desktop">
    <div class="banner_02">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_banner_image_desktop_02')->toHtml(); ?>
        <div class="banner_02_content">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_banner_content_mobile_02')->toHtml(); ?>
        </div>
    </div>
    <div class="banner_03">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_banner_image_desktop_03')->toHtml(); ?>
        <div class="banner_03_content">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_banner_content_mobile_03')->toHtml(); ?>
        </div>
    </div>
</div>