<div class="tiles_end">
    <div class="banner_01">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_banner_image_desktop_07')->toHtml(); ?>
        <div class="banner_01_content">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_banner_content_desktop_07')->toHtml(); ?>
        </div>
    </div>
    <div class="banner_02">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_video')->toHtml(); ?>
    </div>
</div>